services:
    kernel:
        class: Fazland\Rabbitd\Application\Kernel
        synthetic: true

    environment:
        class: Fazland\Rabbitd\Console\Environment
        synthetic: true

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    process:
        class: Fazland\Rabbitd\Process\CurrentProcess

    connection_manager:
        class: Fazland\Rabbitd\Connection\ConnectionManager

    application.output_factory:
        class: Fazland\Rabbitd\Console\OutputFactory
        arguments:
            - '%verbosity%'
        public: false

    application.console_logger:
        class: Psr\Log\LoggerInterface
        synthetic: true

    application.master_output_formatter:
        class: Fazland\Rabbitd\OutputFormatter\LogFormatter
        arguments:
            - 'master'
        public: false

    application.master_output:
        class: Symfony\Component\Console\Output\StreamOutput
        factory: ['@application.output_factory', 'factory']
        arguments:
            - '%log_file%'
        calls:
            - ['setFormatter', ['@application.master_output_formatter']]
        public: false

    application.master_logger:
        class: Symfony\Component\Console\Logger\ConsoleLogger
        arguments:
            - '@application.master_output'
            - []
            -
                warning: 'comment'
        public: false

    application.in_execution_checker:
        class: Fazland\Rabbitd\EventListener\AlreadyInExecutionChecker
        arguments:
            - '%pid_file%'
            - '@process'
        public: false
        tags:
            - { name: event_subscriber }

    application.output_redictor:
        class: Fazland\Rabbitd\EventListener\OutputRedirector
        arguments:
            - '%log_file%'
            - '%verbosity%'
        public: false
        tags:
            - { name: event_subscriber }

    application.process_title_changer:
        class: Fazland\Rabbitd\EventListener\ProcessTitleChanger
        arguments:
            - '@process'
        public: false
        tags:
            - { name: event_subscriber }

    application.signal_dispatcher:
        class: Fazland\Rabbitd\EventListener\SignalDispatcher
        public: false
        tags:
            - { name: event_subscriber }

    application.master_loop_child_checker:
        class: Fazland\Rabbitd\EventListener\MasterLoopChecker
        public: false
        arguments:
            - '@application.master'
        tags:
            - { name: event_subscriber }

    application.master:
        class: Fazland\Rabbitd\Master
        arguments:
            - '@event_dispatcher'
            - '@application.master_logger'
        calls:
            - ['setContainer', ['@service_container']]

    application.children_factory:
        class: Fazland\Rabbitd\ChildrenFactory
        arguments:
            - '@connection_manager'
            - '@application.output_factory'
            - '%log_file%'
            - '@process'
            - '@event_dispatcher'

    application.plugin_manager.composer:
        class: Fazland\Rabbitd\Composer\Composer
        arguments:
            - '%application.root_uri%'

    application.plugin_manager:
        class: Fazland\Rabbitd\Plugin\PluginManager
        arguments:
            - '@application.plugin_manager.composer'
            - '@application.console_logger'
            - '%plugins_dir%'
