imports:
    - { resource: services/ }

services:
    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    process:
        class: Fazland\Rabbitd\Process\CurrentProcess

    connection_manager:
        class: Fazland\Rabbitd\Connection\ConnectionManager

    application.master:
        class: Fazland\Rabbitd\Master
        arguments:
            - '@event_dispatcher'
            - '@application.master_logger'
        calls:
            - ['setContainer', ['@service_container']]

    application.children_factory:
        class: Fazland\Rabbitd\ChildrenFactory
        arguments:
            - '@connection_manager'
            - '@application.output_factory'
            - '%log_file%'
            - '@process'
            - '@event_dispatcher'

    application.plugin_manager.composer:
        class: Fazland\Rabbitd\Composer\Composer
        arguments:
            - '%application.root_uri%'

    application.plugin_manager:
        class: Fazland\Rabbitd\Plugin\PluginManager
        arguments:
            - '@application.plugin_manager.composer'
            - '@logger'
            - '%plugins_dir%'
